package com.su.cse682.infrastructure.persistent.user;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_auth
 */
public class UserAuthDo {
    /**
     * Database Column Remarks:
     *   user authentication unique uuid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     * Database Column Remarks:
     *   instance create time
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   instance modified time
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * Database Column Remarks:
     *   one user to 1many user authentication instance
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   authentication type
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.identity_type
     *
     * @mbg.generated
     */
    private String identityType;

    /**
     * Database Column Remarks:
     *   authentication identifier
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.identifier
     *
     * @mbg.generated
     */
    private String identifier;

    /**
     * Database Column Remarks:
     *   authentication credential
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.credential
     *
     * @mbg.generated
     */
    private String credential;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated
     */
    public UserAuthDo(String uuid, Date gmtCreate, Date gmtModified, String userId, String identityType, String identifier, String credential) {
        this.uuid = uuid;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.userId = userId;
        this.identityType = identityType;
        this.identifier = identifier;
        this.credential = credential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth
     *
     * @mbg.generated
     */
    public UserAuthDo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.uuid
     *
     * @return the value of user_auth.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.uuid
     *
     * @param uuid the value for user_auth.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.gmt_create
     *
     * @return the value of user_auth.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.gmt_create
     *
     * @param gmtCreate the value for user_auth.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.gmt_modified
     *
     * @return the value of user_auth.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.gmt_modified
     *
     * @param gmtModified the value for user_auth.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_id
     *
     * @return the value of user_auth.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_id
     *
     * @param userId the value for user_auth.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.identity_type
     *
     * @return the value of user_auth.identity_type
     *
     * @mbg.generated
     */
    public String getIdentityType() {
        return identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.identity_type
     *
     * @param identityType the value for user_auth.identity_type
     *
     * @mbg.generated
     */
    public void setIdentityType(String identityType) {
        this.identityType = identityType == null ? null : identityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.identifier
     *
     * @return the value of user_auth.identifier
     *
     * @mbg.generated
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.identifier
     *
     * @param identifier the value for user_auth.identifier
     *
     * @mbg.generated
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.credential
     *
     * @return the value of user_auth.credential
     *
     * @mbg.generated
     */
    public String getCredential() {
        return credential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.credential
     *
     * @param credential the value for user_auth.credential
     *
     * @mbg.generated
     */
    public void setCredential(String credential) {
        this.credential = credential == null ? null : credential.trim();
    }
}